coverage_service: cobertura_xml
workspace: QuizApp.xcworkspace
xcodeproj: QuizApp/QuizApp.xcodeproj
scheme: CI
ignore:
  - QuizEngine/QuizEngineTests/*
  - QuizApp/QuizAppTests/*
  - QuizApp/QuizApp/AppDelegate.swift
  - QuizApp/QuizApp/SceneDelegate.swift
binary_basename:
  - QuizApp
  - QuizEngine
